// Chapter 2: AWS Global Infrastructure - flashcard data.
// This is the single source of truth for this chapter's card content as far
// as the HTML viewers are concerned - flashcards.html (this chapter) and
// all_flashcards.html (whole book) both load this same file via <script
// src="...">, so there is only one place to update, not several.
//
// This file itself is generated from flashcards.md and
// deeper_dive_flashcards.md - if those change, regenerate this file to match.
const chapter02Decks = {
  "core": [
    { "term": "Region", "definition": "A broad geographic area where AWS resources can live. Fully isolated from every other region. Customers choose which region their resources run in." },
    { "term": "Availability Zone (AZ)", "definition": "One or more data centers within a region, isolated enough to survive a local disaster on its own, but close enough to other AZs in the same region to work together effectively. A region is made up of multiple AZs." },
    { "term": "Edge Location", "definition": "A small AWS data center that caches content (video, images, other data) close to end users, so requests don't have to travel all the way to the origin server. Cannot process/compute anything - caching and delivery only." },
    { "term": "Amazon CloudFront", "definition": "AWS's CDN (Content Delivery Network). Delivers content through edge locations, checking whether requested data is already cached nearby before going back to the origin. Also handles dynamic content (e.g. real-time dashboards, personalized recommendations), not just static files." },
    { "term": "AWS Local Zone", "definition": "A physical extension of a region, placed in another city to bring AWS infrastructure closer to a specific population of users. Still fully managed by AWS. Used for latency-sensitive workloads (real-time gaming, live production, virtual desktops) where milliseconds matter. Unlike an edge location, a Local Zone can actually process/compute workloads." },
    { "term": "Shared Responsibility Model (Region/AZ context)", "definition": "AWS secures the physical infrastructure, network hardware, power, and cooling, and keeps core services like EC2 and S3 reliable. The customer is responsible for permissions, firewalls, security in the cloud, and patching whatever they deploy (e.g. an EC2 instance they spin up). Most security incidents come from the customer's side of this line, not AWS's." },
    { "term": "Fault Tolerance", "definition": "Redundancy - a backup is already in place before something breaks, so a failure doesn't take the system down." },
    { "term": "High Availability", "definition": "The property of a system continuing to run even when part of it goes down - enabled by spreading infrastructure across multiple Availability Zones connected by private networks, so traffic can fail over almost instantly." },
    { "term": "Data Compliance", "definition": "Some data has to stay within specific geographic areas. Picking the right AWS Region helps meet that requirement." },
    { "term": "Fast Failover", "definition": "The ability to shift workloads to a healthy Availability Zone almost immediately when one AZ has a problem, without losing data." },
    { "term": "Speed (Region/AZ Context)", "definition": "Putting data and resources physically closer to customers reduces the distance data has to travel, making access faster." },
    { "term": "Dynamic Content", "definition": "Content that changes per request, like real-time dashboards or personalized recommendations - CloudFront can deliver this too, not just static cached files." }
  ],
  "deeper": [
    { "term": "AZ Spacing Tradeoff", "definition": "AZs being far enough apart (fault isolation, redundancy) and close enough together (near-instant failover, physical proximity to customers) aren't separate design goals - both come from the same underlying spacing choice AWS makes." },
    { "term": "CloudFront (Router, Not Compute)", "definition": "CloudFront checks whether a request can be served from a nearby cached copy or needs to go back to the origin - it does not run application code. Latency-sensitive compute (real-time gaming, live production) is a Local Zone job, not CloudFront's." },
    { "term": "Region/AZ vs. Edge Locations (Two Separate Systems)", "definition": "Region/AZ is the infrastructure backbone where servers and data live. Edge Locations (run by CloudFront) are a separate, much larger caching network layered on top, not nested inside any AZ. Local Zones are a third, distinct extension of a region for actual compute near users." },
    { "term": "Fault Tolerance vs. High Availability", "definition": "Fault tolerance is the mechanism - a redundant backup ready to take over with zero noticeable impact. High availability is the outcome - the system as a whole stays up. Fault tolerance is one of the main tools used to achieve high availability, not a separate parallel property." },
    { "term": "Multi-AZ Redundancy (Customer Responsibility)", "definition": "AWS's Availability Zones being redundant does not automatically make your application redundant. An application only fails over to another AZ if the customer deliberately architected it to run across multiple AZs (e.g. a load balancer plus instances in multiple AZs, or a Multi-AZ database). This is part of the customer's side of the Shared Responsibility Model, not something AWS does for you automatically." },
    { "term": "Auto Scaling", "definition": "The AWS service that automatically launches new compute instances when demand increases and terminates them again when demand drops, instead of relying on an Availability Zone holding pre-provisioned idle capacity. Often paired with a load balancer distributing traffic across the resulting instances, potentially across multiple AZs. AZs provide redundancy and fault isolation - Auto Scaling is what actually provides capacity elasticity for traffic spikes." },
    { "term": "Elastic Load Balancing (ELB)", "definition": "The missing piece that makes multi-AZ redundancy real: an ELB sits in front of an application, spans multiple AZs, and distributes incoming traffic across whichever instances are currently healthy. It continuously checks instance health - if one instance or an entire AZ goes down, it stops routing traffic there automatically. Instances in multiple AZs without a load balancer means no automatic redirection; a load balancer without instances in more than one AZ means nothing to fail over to. Both pieces are required together." },
    { "term": "Multi-Region vs. Multi-AZ Redundancy", "definition": "Multi-AZ redundancy protects against a single Availability Zone going down, but every AZ used is still inside one Region - it does not protect against a problem affecting the whole Region. Protecting against a full Region outage requires deploying into a second Region as well, a bigger step up in complexity and cost than multi-AZ, and a separate decision from it." },
    { "term": "Cache Refresh (TTL vs. Invalidation)", "definition": "Cached content at an edge location doesn't stay forever. It refreshes either automatically once its TTL (Time To Live) expires, or immediately via an invalidation - an explicit request to drop a specific cached path everywhere right away, useful when you can't wait for the TTL to naturally expire." }
  ]
};
