// Chapter 3: AWS Accounts and Billing - flashcard data.
// This is the single source of truth for this chapter's card content as far
// as the HTML viewers are concerned - flashcards.html (this chapter) and
// all_flashcards.html (whole book) both load this same file via <script
// src="...">, so there is only one place to update, not several.
//
// This file itself is generated from flashcards.md and
// deeper_dive_flashcards.md - if those change, regenerate this file to match.
const chapter03Decks = {
  "core": [
    { "term": "CLI (Command Line Interface)", "definition": "A text-based way to interact with AWS by typing individual commands. Favored by power users and admins because it saves time and allows automation - the most flexible way to interact with AWS." },
    { "term": "Console", "definition": "AWS's web-based graphical interface. Simple, doesn't require coding knowledge - the commands are already there for you, just click through." },
    { "term": "SDK (Software Development Kit)", "definition": "A set of tools for writing code so an application can talk to AWS directly and automatically, without a human running commands. Used to build apps and automated systems that rely on AWS." },
    { "term": "CLI vs. Console vs. SDK", "definition": "All three are ways to interact with AWS, differing by who's doing the interacting and how much automation is involved. Console: a human clicking through a simple graphical interface, no coding required - best for getting started. CLI: a human (or a script they wrote) typing individual commands - flexible, good for automation a person kicks off. SDK: the application's own code talks to AWS directly while running - no human involved at all, used to build software that manages itself." },
    { "term": "AWS Free Tier", "definition": "AWS's way of letting you sample services before committing to paying for them - like a grocery store offering free samples. Aimed at startups, learners, developers, and businesses during the experimentation phase." },
    { "term": "AWS Lambda", "definition": "A serverless compute service that runs code without managing servers. Part of AWS's \"always free\" tier: 1,000,000 requests per month, no matter how long you've had your account." },
    { "term": "DynamoDB", "definition": "A NoSQL database service. Part of AWS's \"always free\" tier: 25 GB of storage included, no matter how long you've had your account." },
    { "term": "Amazon SNS (Simple Notification Service)", "definition": "A messaging/notification service. Part of AWS's \"always free\" tier: 1,000,000 publishes per month." },
    { "term": "AWS Glue DataBrew", "definition": "A visual data preparation tool. Part of AWS's \"always free\" tier: 40 hours of processing per month." },
    { "term": "EC2 (Elastic Compute Cloud)", "definition": "AWS's virtual server service. Included in the 12-month free tier: 750 hours/month of t2.micro or t3.micro usage - enough to keep one instance running continuously all month." },
    { "term": "Amazon S3 (Simple Storage Service)", "definition": "AWS's object storage service. Included in the 12-month free tier: 5 GB of free storage." },
    { "term": "Amazon RDS (Relational Database Service)", "definition": "AWS's managed relational database service. Included in the 12-month free tier: 750 hours/month of usage." },
    { "term": "Amazon Redshift", "definition": "AWS's data warehouse service. Offered as a 30-day free trial - not part of the always-free or 12-month free tiers." },
    { "term": "On-Demand Pricing", "definition": "Pay-as-you-go pricing, billed by the minute, second, or hour - like paying for electricity or water. Best for unpredictable workloads, new projects, and short-term experiments." },
    { "term": "Reserved Pricing", "definition": "Committing to specific services for 1 or 3 years in exchange for a significant discount, up to 72% - like a gym membership. Good fit for production systems and databases." },
    { "term": "Spot Pricing", "definition": "Up to 90% off, but AWS can reclaim the resources at any time. Good for flexible, fault-tolerant workloads like image rendering, big data analysis, and testing environments where occasional interruptions are acceptable." },
    { "term": "On-Demand vs. Reserved vs. Spot Pricing", "definition": "The three pricing models trade commitment for discount. On-Demand: zero commitment, full price, best for unpredictable/new/short-term work. Reserved: commits to 1-3 years for up to 72% off, best for steady long-term workloads like production systems and databases. Spot: bids on unused capacity for up to 90% off, but AWS can reclaim it, so it only fits fault-tolerant, interruptible work." },
    { "term": "Quota", "definition": "A safe default boundary AWS sets on a new account - e.g. how many EC2 instances or static IPs you can create at first. Protects both the customer (from accidentally overspending) and AWS's infrastructure. Limits are flexible - you can request an increase." },
    { "term": "AWS Organizations", "definition": "Lets multiple teams run under a single set of connected AWS accounts, with one main account connecting and managing the others." },
    { "term": "Consolidated Billing", "definition": "A feature of AWS Organizations that combines all linked accounts' charges into a single invoice, like a family's shared budget. Also pools usage across accounts to help reach volume discounts faster." },
    { "term": "AWS Budgets", "definition": "A tool for setting a cost or usage threshold and getting alerted when you're approaching or exceeding it." },
    { "term": "Cost Explorer", "definition": "A tool for visualizing historical AWS spending - by service, account, tag, or time period - to see trends and forecast future costs." }
  ],
  "deeper": [
    { "term": "CLI vs. SDK: Who's Doing the Talking", "definition": "Both let you automate things, but the real difference is who's doing the talking to AWS. CLI: a person (or a script they wrote) runs individual commands - there's always a human behind it somewhere. SDK: the application's own code talks to AWS directly while running - no human typing commands at all. Example: an app that stores every user's photo upload in S3 the moment they upload it uses the SDK, not the CLI - nobody runs a command per upload." },
    { "term": "Exceeding a Free Tier Limit", "definition": "There is no grace period. The moment usage crosses a Free Tier limit, AWS bills the overage at standard On-Demand rates automatically and silently - it just shows up on the normal monthly invoice. The only way to get warned beforehand is to proactively set up a budget alert via AWS Budgets; AWS does not do this automatically." },
    { "term": "Spot Instance Reclaiming (the 2-Minute Warning)", "definition": "When AWS needs Spot capacity back, it gives a 2-minute warning before terminating the instance - the entire window to save state or shut down gracefully, not negotiable and not guaranteed to be any longer. This is why Spot only fits workloads that tolerate sudden interruption (e.g. an overnight batch job), not anything serving live traffic continuously (e.g. a database customers query directly)." },
    { "term": "Requesting a Service Quota Increase", "definition": "Current quotas and increase requests are both handled through the Service Quotas console (or the aws service-quotas CLI). Some requests are approved automatically and near-instantly; others go through manual AWS review. The difference comes down to risk: small increases within normal bounds are low-risk and auto-approved, while large or unusual-looking jumps get manual review to guard against runaway costs or abuse." },
    { "term": "Consolidated Billing's Discount Mechanics", "definition": "AWS pools usage across every linked account in an Organization before applying volume-based discounts, rather than evaluating each account in isolation. Some pricing gets cheaper as usage climbs (e.g. S3's tiered pricing) - pooling usage lets the combined total cross into cheaper tiers faster than any single small account could alone. Reserved capacity works the same way: unused reserved capacity in one account can automatically apply to another linked account's matching usage instead of going to waste. Net effect: smaller departments get pulled into discounts they'd never reach running as a standalone account." },
    { "term": "AWS Budgets vs. Cost Explorer", "definition": "These two tools split the job by time direction. AWS Budgets is forward-looking - set a cost/usage threshold, get alerted when approaching or exceeding it. Cost Explorer is backward-looking - visualizes historical spending by service, account, tag, or time period, and can forecast future costs from that history. Rule of thumb: to find out what already happened, open Cost Explorer; to make sure something doesn't sneak up again, set up AWS Budgets." }
  ]
};
